### ISSUE TITLE
delete/close this repo/package in favor of openkim-models?

### ISSUE THREAD

**Issue by ellio167** [conda-forge/openkimmodels-feedstock#10]
@jan-janssen Why are there two openkim models packages?  We should get rid of this one to avoid confusion, I think.

**Comment by jan-janssen** [comment]
I agree - still I am not sure if we can remove it from conda - I already updated the pyiron related links and I guess it becomes more clear when we simply stop updating this one.

**Comment by ellio167** [comment]
Looks like we should do one or both of these:

https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages

https://conda-forge.org/docs/maintainer/updating_pkgs.html#archiving-feedstocks

**Comment by jan-janssen** [comment]
@ellio167 I just thought about it again and I would suggest to create one last update and only pin `openkim-models` as dependency this way we make sure people have the right package installed.

**Comment by ellio167** [comment]
Sure, a release pointing to openkim-models would be good.  Then, I guess we could gave the repo archived so it’s clear that no further updates will occur.  Good idea!
