### ISSUE TITLE
name: openkimmodels vs. openkim-models

### ISSUE THREAD

**Issue by ellio167** [conda-forge/openkimmodels-feedstock#5]
@jan-janssen any reason this is named without the dash as opposed to with a dash (which is how this package is named in all of our other binary distributions)?

**Comment by jan-janssen** [comment]
I guess that was just my personal preference, but we can change it. I am going to contact the conda-forge core team about how to do it.

**Comment by jan-janssen** [comment]
We can rename the package by creating a new pull request, so that is definitely something we can do once we get it working.
https://conda-forge.org/docs/orga/guidelines.html?highlight=rename#renaming-packages
